// src/components/reports/ReportStatusModal.jsx

import { useState } from 'react';
import { X, CheckCircle, XCircle, AlertCircle, Save } from 'lucide-react';
import { reportService } from '../../services/reportService';
import toast from 'react-hot-toast';

const ReportStatusModal = ({ isOpen, onClose, report, onSuccess }) => {
  const [status, setStatus] = useState(report?.report_status || 'pending');
  const [reviewComments, setReviewComments] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!status) {
      toast.error('Please select a status');
      return;
    }

    try {
      setLoading(true);
      await reportService.updateStatus(report.inspection_id, status, reviewComments);
      toast.success('Report status updated successfully');
      
      if (onSuccess) onSuccess();
      onClose();
    } catch (error) {
      const errorMsg = error.response?.data?.error || 'Failed to update status';
      toast.error(errorMsg);
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen || !report) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg">
        {/* Header */}
        <div className="bg-gradient-to-r from-primary-600 to-accent-600 px-6 py-4 flex items-center justify-between rounded-t-2xl">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-white/20 rounded-lg flex items-center justify-center">
              <CheckCircle className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white">Update Report Status</h2>
              <p className="text-sm text-white/80">{report.report_number}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-white/20 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-white" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-6 space-y-4">
          {/* Report Info */}
          <div className="bg-neutral-50 rounded-lg p-4">
            <div className="grid grid-cols-2 gap-3 text-sm">
              <div>
                <span className="text-neutral-600">Vessel:</span>
                <p className="font-medium text-neutral-900">{report.vessel_tag}</p>
              </div>
              <div>
                <span className="text-neutral-600">Generated By:</span>
                <p className="font-medium text-neutral-900">{report.generated_by_name || '-'}</p>
              </div>
            </div>
          </div>

          {/* Status Selection */}
          <div>
            <label className="block text-sm font-medium text-neutral-700 mb-2">
              Review Status *
            </label>
            <div className="space-y-2">
              <label className="flex items-center gap-3 p-3 border-2 rounded-lg cursor-pointer hover:bg-neutral-50 transition-colors">
                <input
                  type="radio"
                  value="approved"
                  checked={status === 'approved'}
                  onChange={(e) => setStatus(e.target.value)}
                  className="w-4 h-4 text-green-600"
                />
                <CheckCircle className="w-5 h-5 text-green-600" />
                <div>
                  <p className="font-medium text-neutral-900">Approved</p>
                  <p className="text-xs text-neutral-600">Report meets all requirements</p>
                </div>
              </label>

              <label className="flex items-center gap-3 p-3 border-2 rounded-lg cursor-pointer hover:bg-neutral-50 transition-colors">
                <input
                  type="radio"
                  value="changes_requested"
                  checked={status === 'changes_requested'}
                  onChange={(e) => setStatus(e.target.value)}
                  className="w-4 h-4 text-amber-600"
                />
                <AlertCircle className="w-5 h-5 text-amber-600" />
                <div>
                  <p className="font-medium text-neutral-900">Changes Requested</p>
                  <p className="text-xs text-neutral-600">Requires modifications</p>
                </div>
              </label>

              <label className="flex items-center gap-3 p-3 border-2 rounded-lg cursor-pointer hover:bg-neutral-50 transition-colors">
                <input
                  type="radio"
                  value="rejected"
                  checked={status === 'rejected'}
                  onChange={(e) => setStatus(e.target.value)}
                  className="w-4 h-4 text-red-600"
                />
                <XCircle className="w-5 h-5 text-red-600" />
                <div>
                  <p className="font-medium text-neutral-900">Rejected</p>
                  <p className="text-xs text-neutral-600">Does not meet standards</p>
                </div>
              </label>
            </div>
          </div>

          {/* Review Comments */}
          <div>
            <label className="block text-sm font-medium text-neutral-700 mb-2">
              Review Comments
            </label>
            <textarea
              value={reviewComments}
              onChange={(e) => setReviewComments(e.target.value)}
              rows={4}
              className="w-full px-4 py-2 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
              placeholder="Enter any comments or feedback..."
            />
          </div>

          {/* Footer */}
          <div className="flex justify-end gap-3 pt-4">
            <button
              type="button"
              onClick={onClose}
              className="px-6 py-2.5 border border-neutral-300 text-neutral-700 font-medium rounded-lg hover:bg-neutral-50 transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="btn-primary px-6 py-2.5 flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Save className="w-5 h-5" />
              {loading ? 'Updating...' : 'Update Status'}
            </button>
            </div>
        </form>
      </div>
    </div>
  );
};

export default ReportStatusModal;